PLUGIN_NAME=		arpwatch
PLUGIN_VERSION=		0.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Network traffic monitor
PLUGIN_DEPENDS=		arpwatch
PLUGIN_MAINTAINER=	coopercc06@gmail.com

.include "../../Mk/plugins.mk"
