PLUGIN_NAME=	arpmonitor
PLUGIN_VERSION=	0.1
PLUGIN_COMMENT=	Network Traffick monitor utilizing arpwatch and nmap
PLUGIN_DEPENDS=	arpwatch nmap
PLUGIN_MAINTAINER=	coopercc06@gmail.com

.include "../../Mk/plugins.mk"
